/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LTE
{
  public enum DefectType
  {
    Weak = 0,
    Excessive = 1,
    Overlapped = 2,
    PCIconflict = 3,
    PCIconfusion = 4,
    PCImod3 = 5,
  }
}
